Added simple GUI for Anonsurf

diff --git a/anonsurf-deb-src/etc/init.d/anonsurf b/anonsurf-deb-src/etc/init.d/anonsurf
--- a/anonsurf-deb-src/etc/init.d/anonsurf
+++ b/anonsurf-deb-src/etc/init.d/anonsurf
@@ -39,30 +39,29 @@ fi
 # Functions
 #-----------------------------------------------------------------------------
 
-### Stopping common apps and deleting history/cookies/caches etc
+### Stop common apps and deleting history/cookies/caches etc
 function init {
-	echo -e "${GREEN}>>>${BLUE} Killing caching applications...$RESETCOLOR"
+	echo -e "${GREEN}>>>${BLUE} Killing caching applications${RESETCOLOR}"
 	killall -q chrome dropbox iceweasel skype icedove thunderbird firefox chromium xchat transmission deluge pidgin pidgin.orig
-	echo -e "${GREEN}>>>${BLUE} Cleaning application caches..."
+	echo -e "${GREEN}>>>${BLUE} Cleaning application caches"
 	bleachbit -c adobe_reader.cache chromium.cache chromium.current_session chromium.history elinks.history emesene.cache epiphany.cache firefox.url_history flash.cache flash.cookies google_chrome.cache google_chrome.history  links2.history opera.cache opera.search_history opera.url_history &> /dev/null
 }
 
 
 ### Starting I2P services
 function starti2p {
-	echo -e "${GREEN}>>>${BLUE} Starting I2P services...$RESETCOLOR"
+	echo -e "${GREEN}>>>${BLUE} Starting I2P services${RESETCOLOR}"
 	service tor stop
 	# Modify DNS settings
-	if [ "$resolvconf_support" = false ]
-	then
+	if [ "$resolvconf_support" = false ]; then
 		cp /etc/resolv.conf /etc/resolv.conf.bak;
 		touch /etc/resolv.conf;
 		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' > /etc/resolv.conf;
-		echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Modified resolv.conf to use localhost and Private Internet Access DNS.$RESETCOLOR";
+		echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Modified resolv.conf to use localhost and Private Internet Access DNS.${RESETCOLOR}";
 	else
 		cp /etc/resolvconf/resolv.conf.d/head{,.bak};
 		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' >> /etc/resolvconf/resolv.conf.d/head;
-		echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Modified resolvconf to use localhost and Private Internet Access DNS.$RESETCOLOR";
+		echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Modified resolvconf to use localhost and Private Internet Access DNS.${RESETCOLOR}";
 		resolvconf -u;
 	fi
 	sudo -u i2psvc i2prouter start
@@ -73,12 +72,11 @@ function starti2p {
 
 ### Stopping I2P services and restoring DNS resolution settings
 function stopi2p {
-	echo -e "${GREEN}>>>${BLUE} Stopping I2P services...$RESETCOLOR"
+	echo -e "${GREEN}>>>${BLUE} Stopping I2P services${RESETCOLOR}"
 	sudo -u i2psvc i2prouter stop
 
 	# restore DNS settings
-	if [ "$resolvconf_support" = false ]
-	then
+	if [ "$resolvconf_support" = false ]; then
 		if [ -e /etc/resolv.conf.bak ]; then
 			rm /etc/resolv.conf
 			cp /etc/resolv.conf.bak /etc/resolv.conf
@@ -92,21 +90,35 @@ function stopi2p {
 
 ### Show IP address information
 function ip {
-	echo -e "${GREEN}>>>${BLUE} Getting IP address...$RESETCOLOR"
+	echo -e "${GREEN}>>>${BLUE} Getting IP address${RESETCOLOR}"
 	myip=`curl -s "http://myexternalip.com/raw"`
 	echo "IP Address: ${myip}"
 	#
 	if [[ -z "$(command -v curl)" ]] ; then
 		echo "Error: curl command not installed. Cannot retrieve IP geo details"
 	else
-		echo -e "${GREEN}>>>${BLUE} Getting geo location for IP address...$RESETCOLOR"
+		echo -e "${GREEN}>>>${BLUE} Geo location details${RESETCOLOR}"
 		if [[ -z "$(command -v xq)" ]] ; then
 			curl -s curl -s http://ip-api.com/xml/${myip}
 		else
 			curl -s curl -s http://ip-api.com/xml/${myip} | xq
 		fi
 	fi
+}
 
+
+### Show IP address information
+function ipinfo {
+   myip=`curl -s "http://myexternalip.com/raw"`
+   echo "IP Address:"
+   echo "${myip}"
+   #
+   if [[ -z "$(command -v curl)" ]] ; then
+      echo "Error: curl command not installed. Cannot retrieve IP geo details"
+   else
+      echo "Geo location details:"
+		curl -s http://ip-api.com/line/${myip}
+   fi
 }
 
 
@@ -114,56 +126,58 @@ function ip {
 function start {
 	# Make sure only root can run this script
 	if [ $(id -u) -ne 0 ]; then
-		echo -e -e "${GREEN}[$RED!${GREEN}] $RED This script must be run as root.$RESETCOLOR" >&2
+		echo -e -e "${GREEN}[$RED!${GREEN}] $RED This script must be run as root.${RESETCOLOR}" >&2
 		exit 1
 	fi
 
 	# Check defaults for Tor
 	grep -q -x 'RUN_DAEMON="yes"' /etc/default/tor
 	if [ $? -ne 0 ]; then
-		echo -e "${GREEN}[$RED!${GREEN}]$RED Please add the following to your /etc/default/tor and restart service:$RESETCOLOR" >&2
-		echo -e "${BLUE}#----------------------------------------------------------------------#$RESETCOLOR"
+		echo -e "${GREEN}[$RED!${GREEN}]$RED Please add the following to your /etc/default/tor and restart service:${RESETCOLOR}" >&2
+		echo -e "${BLUE}#----------------------------------------------------------------------#${RESETCOLOR}"
 		echo -e 'RUN_DAEMON="yes"'
-		echo -e "${BLUE}#----------------------------------------------------------------------#$RESETCOLOR"
+		echo -e "${BLUE}#----------------------------------------------------------------------#${RESETCOLOR}"
 		exit 1
-        fi
+   fi
+	
 	# Kill IPv6 services
-	echo -e "${GREEN}>>>${BLUE} Stopping IPv6 services...$RESETCOLOR"
+	echo -e "${GREEN}>>>${BLUE} Stopping IPv6 services${RESETCOLOR}"
 	sed -i '/^.*\#anonsurf$/d' /etc/sysctl.conf #delete lines containing #anonsurf in /etc/sysctl.conf
+	
 	# add lines to sysctl.conf that will kill ipv6 services
 	echo "net.ipv6.conf.all.disable_ipv6 = 1 #anonsurf" >> /etc/sysctl.conf
 	echo "net.ipv6.conf.default.disable_ipv6=1 #anonsurf" >> /etc/sysctl.conf
 	sysctl -p > /dev/null  # have sysctl reread /etc/sysctl.conf
 
-	echo -e "${GREEN}>>>${BLUE} Starting anonymous mode...$RESETCOLOR"
+	echo -e "${GREEN}>>>${BLUE} Starting anonymous mode${RESETCOLOR}"
 	
 	if [ ! -e /var/run/tor/tor.pid ]; then
-		echo -e "$RED>>>${BLUE} Tor is not running. Starting...$RESETCOLOR" >&2
+		echo -e "$RED>>>${BLUE} Tor is not running. Starting${RESETCOLOR}" >&2
 		service network-manager force-reload > /dev/null 2>&1
 		killall dnsmasq > /dev/null 2>&1
 		killall nscd > /dev/null 2>&1	
 		service tor start
 		sleep 1
 	fi
+	
 	if ! [ -f /etc/network/iptables.rules ]; then
 		iptables-save > /etc/network/iptables.rules
-		echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Saved iptables rules.$RESETCOLOR"
+		echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Saved iptables rules.${RESETCOLOR}"
 	fi
 	
 	iptables -F
 	iptables -t nat -F
 	
-	if [ "$resolvconf_support" = false ] 
-	then
+	if [ "$resolvconf_support" = false ] ; then
 		cp /etc/resolv.conf /etc/resolv.conf.bak
 		touch /etc/resolv.conf
 		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' > /etc/resolv.conf
-		echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Modified resolv.conf to use Tor and Private Internet Access DNS.$RESETCOLOR"
+		echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Modified resolv.conf to use Tor and Private Internet Access DNS.${RESETCOLOR}"
 	else
 		cp /etc/resolvconf/resolv.conf.d/head{,.bak}
-        echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' >> /etc/resolvconf/resolv.conf.d/head
-        echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Modified resolvconf to use localhost and Private Internet Access DNS.$RESETCOLOR"
-        resolvconf -u
+      echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' >> /etc/resolvconf/resolv.conf.d/head
+      echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Modified resolvconf to use localhost and Private Internet Access DNS.${RESETCOLOR}"
+      resolvconf -u
 	fi
 
 	# set iptables nat
@@ -198,8 +212,8 @@ function start {
 	iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
 	iptables -A OUTPUT -j REJECT
 
-	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} All traffic was redirected through Tor.$RESETCOLOR"
-	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} You are under AnonSurf tunnel!$RESETCOLOR"
+	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} All traffic was redirected through Tor.${RESETCOLOR}"
+	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} You are under AnonSurf tunnel!${RESETCOLOR}"
 }
 
 
@@ -207,14 +221,14 @@ function start {
 function stop {
 	# Make sure only root can run our script
 	if [ $(id -u) -ne 0 ]; then
-		echo -e "${GREEN}[$RED!${GREEN}] $RED This script must be run as root.$RESETCOLOR" >&2
+		echo -e "${GREEN}[$RED!${GREEN}] $RED This script must be run as root.${RESETCOLOR}" >&2
 		exit 1
 	fi
-	echo -e "${GREEN}>>>${BLUE} Stopping anonymous mode...$RESETCOLOR"
+	echo -e "${GREEN}>>>${BLUE} Stopping anonymous mode${RESETCOLOR}"
 
 	iptables -F
 	iptables -t nat -F
-	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Deleted all iptables rules.$RESETCOLOR"
+	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Deleted all iptables rules.${RESETCOLOR}"
 	
 	if [ -f /etc/network/iptables.rules ]; then
 		iptables-restore < /etc/network/iptables.rules
@@ -223,8 +237,7 @@ function stop {
 	fi
 	
 	# restore DNS settings
-	if [ "$resolvconf_support" = false ] 
-	then
+	if [ "$resolvconf_support" = false ]; then
 		if [ -e /etc/resolv.conf.bak ]; then
 			rm /etc/resolv.conf
 			cp /etc/resolv.conf.bak /etc/resolv.conf
@@ -236,7 +249,7 @@ function stop {
 	
 	service tor stop
 	
-	echo -e "${GREEN}>>>${BLUE} Reenabling IPv6 services...$RESETCOLOR"
+	echo -e "${GREEN}>>>${BLUE} Reenabling IPv6 services${RESETCOLOR}"
 
 	# reenable IPv6 services
 	sed -i '/^.*\#anonsurf$/d' /etc/sysctl.conf #delete lines containing #anonsurf in /etc/sysctl.conf
@@ -246,7 +259,7 @@ function stop {
 	service nscd start > /dev/null 2>&1
 	service dnsmasq start > /dev/null 2>&1
 	
-	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Anonymous mode stopped.$RESETCOLOR"
+	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Anonymous mode stopped.${RESETCOLOR}"
 }
 
 
@@ -254,7 +267,7 @@ function stop {
 function change {
 	service tor reload
 	sleep 2
-	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Tor daemon reloaded and forced to change nodes.$RESETCOLOR"
+	echo -e "${GREEN}[${BLUE}i${GREEN}]${BLUE} Tor daemon reloaded and forced to change nodes.${RESETCOLOR}"
 }
 
 
@@ -289,6 +302,9 @@ case "$1" in
 	myip|ip)
 		ip
 	;;
+	ipinfo)
+      ipinfo
+   ;;
 	starti2p)
 		starti2p
 	;;
@@ -301,25 +317,25 @@ case "$1" in
 		$0 start
 	;;
    *)
-echo -e "
-AnonSurf Module
-	Usage:
-	anonsurf $RED{${GREEN}""start$RED|${GREEN}""stop$RED|${GREEN}""restart$RED|${GREEN}""change$RED""$RED|${GREEN}""status$RED""}
-	
-	$RED start${BLUE} -${GREEN} Start system-wide anonymous tunneling under TOR proxy through iptables	  
-	$RED stop${BLUE} -${GREEN} Reset original iptables settings and return to clear navigation
-	$RED restart${BLUE} -${GREEN} Combines \"stop\" and \"start\" options
-	$RED change${BLUE} -${GREEN} Changes identity restarting TOR
-	$RED status${BLUE} -${GREEN} Check if AnonSurf is working properly
-	$RED myip${BLUE} -${GREEN} Show your current IP address
-	----[ I2P related features ]----
-	$RED starti2p${BLUE} -${GREEN} Start i2p services
-	$RED stopi2p${BLUE} -${GREEN} Stop i2p services
-	
-$RESETCOLOR" >&2
-exit 1
-;;
+		echo -e "
+		AnonSurf Module
+			Usage:
+			anonsurf $RED{${GREEN}""start$RED|${GREEN}""stop$RED|${GREEN}""restart$RED|${GREEN}""change$RED""$RED|${GREEN}""status$RED""}
+			
+			$RED start${BLUE} -${GREEN} Start system-wide anonymous tunneling under TOR proxy through iptables	  
+			$RED stop${BLUE} -${GREEN} Reset original iptables settings and return to clear navigation
+			$RED restart${BLUE} -${GREEN} Combines \"stop\" and \"start\" options
+			$RED change${BLUE} -${GREEN} Changes identity restarting TOR
+			$RED status${BLUE} -${GREEN} Check if AnonSurf is working properly
+			$RED ip${BLUE} -${GREEN} Show your current IP address
+			----[ I2P related features ]----
+			$RED starti2p${BLUE} -${GREEN} Start i2p services
+			$RED stopi2p${BLUE} -${GREEN} Stop i2p services
+			
+		${RESETCOLOR}" >&2
+		exit 1
+		;;
 esac
 
-echo -e $RESETCOLOR
+echo -e ${RESETCOLOR}
 exit 0
