Tightened security a bit

diff --git a/anonsurf-deb-src/etc/init.d/anonsurf b/anonsurf-deb-src/etc/init.d/anonsurf
--- a/anonsurf-deb-src/etc/init.d/anonsurf
+++ b/anonsurf-deb-src/etc/init.d/anonsurf
@@ -91,18 +91,18 @@ function stopi2p {
 ### Show IP address information
 function ip {
 	echo -e "${GREEN}>>>${BLUE} Getting IP address${RESETCOLOR}"
-	myip=$(curl -s ifconfig.me)
+	myip=$(curl -s icanhazip.com)
 	echo "IP Address: ${myip}"
 	#
 	echo -e "${GREEN}>>>${BLUE} Geo location details${RESETCOLOR}"
-	curl -s curl -s http://ip-api.com/xml/${myip}?fields=135161
+	curl -s http://ip-api.com/xml/${myip}?fields=4089
 }
 
 
 ### Show IP address information
 function ipinfo {
-	myip=$(curl -s ifconfig.me)
-	curl -s http://ip-api.com/xml/${myip}?fields=143353
+	myip=$(curl -s icanhazip.com)
+	curl -s http://ip-api.com/xml/${myip}?fields=12281
 }
 
 
@@ -283,6 +283,12 @@ function checkDependencies {
 	fi
 }
 
+function init {
+   if [ $(id -u) -ne 0 ]; then
+      echo "Error. Must be run as root or with sudo privileges."
+      exit 1
+   fi
+}
 
 
 #-----------------------------------------------------------------------------
@@ -290,6 +296,7 @@ function checkDependencies {
 #-----------------------------------------------------------------------------
 
 # Pre-flight checks
+init
 checkDependencies
 
 
diff --git a/anonsurf-deb-src/usr/bin/anonsurf-gui b/anonsurf-deb-src/usr/bin/anonsurf-gui
--- a/anonsurf-deb-src/usr/bin/anonsurf-gui
+++ b/anonsurf-deb-src/usr/bin/anonsurf-gui
@@ -23,20 +23,14 @@ function init {
     # Are we root? If not, ask for sudo password
     if [ $(id -u) -ne 0 ]; then
         # sudo without password possible?
-        if sudo -n true ; then
-            # All good
-            echo "User $UID has sudo privileges."
-        else 
+        if ! sudo -n true ; then
             export PASSWD=$(zenity --password)
             if [ -z $PASSWD ] ; then
-                echo "Error: no password entered. Aborting..."
+                echo "Error: no password entered. Aborting."
                 exit 1
             fi
         fi
-    else
-        export ISROOT=true
     fi
-
 }
 
 
@@ -53,7 +47,7 @@ checkDependencies
 # Main loop
 while true
 do
-    MESSAGE="Tor status: $(systemctl is-active tor)\nIP address: $(curl -s ifconfig.me)"
+    MESSAGE="Tor status: $(systemctl is-active tor)\nIP address: $(curl -s icanhazip.com)"
 
     ### Main menu, displaying Tor actions
     action=$(zenity --list \
@@ -75,17 +69,17 @@ do
     if [ $? = 0 ]; then
         case "$action" in
             info)
-                /etc/init.d/anonsurf ipinfo > /tmp/ip
+                echo $PASSWD | sudo -S /etc/init.d/anonsurf ipinfo > /tmp/ip
                 zenity --text-info --title="IP address details" --filename=/tmp/ip --width=400 --height=500
                 ;;
             start)
                 (echo $PASSWD | sudo -S /etc/init.d/anonsurf start) | zenity --progress --title="Anonsurf" --text="Starting anonymous browsing mode..." --percentage=0
-                MESSAGE="Anonymous browsing service successfully started\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s ifconfig.me)"
+                MESSAGE="Anonymous browsing service successfully started\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s icanhazip.com)"
                 zenity --notification --text="${MESSAGE}"
                 ;;
             stop)
                 (echo $PASSWD | sudo -S /etc/init.d/anonsurf stop) | zenity --progress --title="Anonsurf" --text="Stopping anonymous browsing mode..." --percentage=0
-                MESSAGE="Anonymous browsing service has been stopped\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s ifconfig.me)"
+                MESSAGE="Anonymous browsing service has been stopped\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s icanhazip.com)"
                 zenity --notification --text="${MESSAGE}"
                 ;;
             change)
@@ -95,12 +89,12 @@ do
                 ;;
             starti2p)
                 (echo $PASSWD | sudo -S /etc/init.d/anonsurf starti2p) | zenity --progress --title="Anonsurf" --text="Starting I2P service..." --percentage=0
-                MESSAGE="I2P service successfully started\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s ifconfig.me)"
+                MESSAGE="I2P service successfully started\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s icanhazip.com)"
                 zenity --notification --text="${MESSAGE}"
                 ;;
             stopi2p)
                 (echo $PASSWD | sudo -S /etc/init.d/anonsurf stopi2p) | zenity --progress --title="Anonsurf" --text="Stopping I2P service..." --percentage=0
-                MESSAGE="I2P service has been stopped\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s ifconfig.me)"
+                MESSAGE="I2P service has been stopped\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s icanhazip.com)"
                 zenity --notification --text="${MESSAGE}"
                 ;;
         esac
