Code cleanup

diff --git a/anonsurf-deb-src/etc/init.d/anonsurf b/anonsurf-deb-src/etc/init.d/anonsurf
--- a/anonsurf-deb-src/etc/init.d/anonsurf
+++ b/anonsurf-deb-src/etc/init.d/anonsurf
@@ -40,7 +40,7 @@ fi
 #-----------------------------------------------------------------------------
 
 ### Stop common apps and deleting history/cookies/caches etc
-function init {
+function cleanup {
 	echo -e "${GREEN}>>>${BLUE} Killing caching applications${RESETCOLOR}"
 	killall -q chrome dropbox iceweasel skype icedove thunderbird firefox chromium xchat transmission deluge pidgin pidgin.orig
 	echo -e "${GREEN}>>>${BLUE} Cleaning application caches"
@@ -91,31 +91,18 @@ function stopi2p {
 ### Show IP address information
 function ip {
 	echo -e "${GREEN}>>>${BLUE} Getting IP address${RESETCOLOR}"
-	myip=`curl ifconfig.me`
-
+	myip=$(curl -s ifconfig.me)
 	echo "IP Address: ${myip}"
 	#
-	if [[ -z "$(command -v curl)" ]] ; then
-		echo "Error: curl command not installed. Cannot retrieve IP geo details"
-	else
-		echo -e "${GREEN}>>>${BLUE} Geo location details${RESETCOLOR}"
-		if [[ -z "$(command -v xq)" ]] ; then
-			curl -s curl -s http://ip-api.com/xml/${myip}?fields=135161
-		else
-			curl -s curl -s http://ip-api.com/xml/${myip}?fields=135161 | xq
-		fi
-	fi
+	echo -e "${GREEN}>>>${BLUE} Geo location details${RESETCOLOR}"
+	curl -s curl -s http://ip-api.com/xml/${myip}?fields=135161
 }
 
 
 ### Show IP address information
 function ipinfo {
-   if [[ -z "$(command -v curl)" ]] ; then
-      echo "Error: curl command not installed. Cannot retrieve IP geo details"
-   else
-   	myip=`curl -s "http://myexternalip.com/raw"`
-		curl -s http://ip-api.com/xml/${myip}?fields=143353
-   fi
+	myip=$(curl -s ifconfig.me)
+	curl -s http://ip-api.com/xml/${myip}?fields=143353
 }
 
 
@@ -274,20 +261,46 @@ function status {
 }
 
 
+function checkDependencies {
+	# Tor
+	if ! [ -x "$(command -v tor)" ]; then
+		echo 'Error: Tor is not installed.' >&2
+		exit 1
+	fi
+	# iptables firewall
+	if ! [ -x "$(command -v iptables)" ]; then
+		echo 'Error: iptables is not installed.' >&2
+		exit 1
+	fi
+	# Bleachbit
+	if ! [ -x "$(command -v bleachbit)" ]; then
+		echo 'Warning: bleachbit is not installed. Anonsurf will not be able to clean up your system.' >&2
+	fi
+	# Curl
+	if ! [ -x "$(command -v curl)" ]; then
+		echo 'Error: Curl is not installed.' >&2
+		exit 1
+	fi
+}
+
 
 
 #-----------------------------------------------------------------------------
 # Main section
 #-----------------------------------------------------------------------------
 
+# Pre-flight checks
+checkDependencies
 
+
+# Main loop
 case "$1" in
 	start)
-		init
+		cleanup
 		start
 	;;
 	stop)
-		init
+		cleanup
 		stop
 	;;
 	change)
diff --git a/anonsurf-deb-src/usr/bin/anonsurf-gui b/anonsurf-deb-src/usr/bin/anonsurf-gui
--- a/anonsurf-deb-src/usr/bin/anonsurf-gui
+++ b/anonsurf-deb-src/usr/bin/anonsurf-gui
@@ -1,34 +1,74 @@
 #!/usr/bin/env bash
 
-if [ $(id -u) -ne 0 ]; then
-    export PASSWD=$(zenity --password)
-    if [ -z $PASSWD ] ; then
-        echo "Error: no password entered. Aborting..."
+function checkDependencies {
+    # Tor
+    if ! [ -f /etc/init.d/anonsurf ]; then
+        echo 'Error: Anonsurf CLI is not installed.' >&2
         exit 1
     fi
-fi
+    # Zenity
+    if ! [ -x "$(command -v zenity)" ]; then
+        echo 'Error: Zenity is not installed.' >&2
+        exit 1
+    fi
+    # Curl
+    if ! [ -x "$(command -v curl)" ]; then
+        echo 'Error: Curl is not installed.' >&2
+        exit 1
+    fi
+}
 
 
+function init {
+    # Are we root? If not, ask for sudo password
+    if [ $(id -u) -ne 0 ]; then
+        # sudo without password possible?
+        if sudo -n true ; then
+            # All good
+            echo "User $UID has sudo privileges."
+        else 
+            export PASSWD=$(zenity --password)
+            if [ -z $PASSWD ] ; then
+                echo "Error: no password entered. Aborting..."
+                exit 1
+            fi
+        fi
+    else
+        export ISROOT=true
+    fi
+
+}
+
+
+#-----------------------------------------------------------------------------
+# Main section
+#-----------------------------------------------------------------------------
+
+
+# Pre-flight checks
+init
+checkDependencies
+
+
+# Main loop
 while true
 do
-    STATUS=$(systemctl is-active tor)
-    IP=$(curl ifconfig.me)
-    MESSAGE="** Tor status: ${STATUS} **\n** IP address: ${IP} **"
+    MESSAGE="Tor status: $(systemctl is-active tor)\nIP address: $(curl -s ifconfig.me)"
 
     ### Main menu, displaying Tor actions
     action=$(zenity --list \
-        --text="${MESSAGE}\n\nSelect the desired action from the list below"\
+        --text="${MESSAGE}\n\nSelect the desired action and click OK, or click CANCEL to quit."\
         --title "Anonsurf" \
         --radiolist \
-        --column "Selected" \
+        --column "" \
         --column "Action"\
         --column "Description" \
-            FALSE "start"    "Start the anonymous browsing service"\
-            FALSE "stop"     "Stop the anonymous browsing service"\
-            FALSE "change"   "Change Tor exit node"\
-            FALSE "starti2p" "Start I2P services" \
-            FALSE "stopi2p"  "Stop I2P services" \
-            True  "info"     "Display current IP address details"\
+            TRUE "start" "Start the Tor anonymous browsing service "\
+            FALSE "stop" "Stop the Tor anonymous browsing service"\
+            FALSE "change" "Change public IP address and location"\
+            FALSE "starti2p" "Start I2P service, a fully encrypted private network layer" \
+            FALSE "stopi2p" "Stop I2P service" \
+            FALSE  "info" "Display current IP address details"\
         --height=400 \
         --width=500)
         
@@ -39,17 +79,13 @@ do
                 zenity --text-info --title="IP address details" --filename=/tmp/ip --width=400 --height=500
                 ;;
             start)
-                (echo $PASSWD | sudo -S /etc/init.d/anonsurf start) | zenity --progress --title="Anonsurf" --text="Starting anonymous mode..." --percentage=0
-                STATUS=$(systemctl is-active tor)
-                IP=$(curl ifconfig.me)
-                MESSAGE="Anonsurf notification\nAnonymous mode enabled\n- Tor status: ${STATUS}\n- IP address: ${IP}"
+                (echo $PASSWD | sudo -S /etc/init.d/anonsurf start) | zenity --progress --title="Anonsurf" --text="Starting anonymous browsing mode..." --percentage=0
+                MESSAGE="Anonymous browsing service successfully started\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s ifconfig.me)"
                 zenity --notification --text="${MESSAGE}"
                 ;;
             stop)
-                (echo $PASSWD | sudo -S /etc/init.d/anonsurf stop) | zenity --progress --title="Anonsurf" --text="Stopping anonymous mode..." --percentage=0
-                STATUS=$(systemctl is-active tor)
-                IP=$(wget -qO- eth0.me)
-                MESSAGE="Anonsurf notification\nAnonymous mode stopped\n- Tor status: ${STATUS}\n- IP address: ${IP}"
+                (echo $PASSWD | sudo -S /etc/init.d/anonsurf stop) | zenity --progress --title="Anonsurf" --text="Stopping anonymous browsing mode..." --percentage=0
+                MESSAGE="Anonymous browsing service has been stopped\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s ifconfig.me)"
                 zenity --notification --text="${MESSAGE}"
                 ;;
             change)
@@ -58,17 +94,13 @@ do
                 zenity --notification --text="${MESSAGE}"
                 ;;
             starti2p)
-                (echo $PASSWD | sudo -S /etc/init.d/anonsurf starti2p) | zenity --progress --title="Anonsurf" --text="Starting I2P mode..." --percentage=0
-                STATUS=$(systemctl is-active tor)
-                IP=$(wget -qO- eth0.me)
-                MESSAGE="I2P service started\n- Tor status: ${STATUS}\n- IP address: ${IP}"
+                (echo $PASSWD | sudo -S /etc/init.d/anonsurf starti2p) | zenity --progress --title="Anonsurf" --text="Starting I2P service..." --percentage=0
+                MESSAGE="I2P service successfully started\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s ifconfig.me)"
                 zenity --notification --text="${MESSAGE}"
                 ;;
             stopi2p)
-                (echo $PASSWD | sudo -S /etc/init.d/anonsurf stopi2p) | zenity --progress --title="Anonsurf" --text="Stopping I2P mode..." --percentage=0
-                STATUS=$(systemctl is-active tor)
-                IP=$(wget -qO- eth0.me)
-                MESSAGE="I2P service stopped\n- Tor status: ${STATUS}\n- IP address: ${IP}"
+                (echo $PASSWD | sudo -S /etc/init.d/anonsurf stopi2p) | zenity --progress --title="Anonsurf" --text="Stopping I2P service..." --percentage=0
+                MESSAGE="I2P service has been stopped\n- Tor status: $(systemctl is-active tor)\n- IP address: $(curl -s ifconfig.me)"
                 zenity --notification --text="${MESSAGE}"
                 ;;
         esac
